config/routes.rb
Rails.application.routes.draw do
    devise_for :users
  resources :recipes
  root 'recipes#index'
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "400x400#"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :name, presence: true
  has_many :directions, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :directions, :allow_destroy => true
  accepts_nested_attributes_for :ingredients, :allow_destroy => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :update, :edit, :destroy]

  def index
    @recipe = Recipe.all
  end

  def show
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_param)
    if @recipe.save
      redirect_to @recipe
    else
      redirect_to 'new'
    end
  end

  def update
    if @recipe.update(recipe_param)
      redirect_to @recipe
    else
      redirect_to 'edit'
    end
  end

  def edit
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  private
  def recipe_param
    params.require(:recipe).permit(:name, :description, :image, ingredients_attributes: [:id, :name, :_destroy],
      directions_attributes: [:id, :step, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Syntagi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="navbar-brand">
        <%= link_to 'syntagi', root_path %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Find</button>
      </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'New Recipe', new_recipe_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<p style="margin:0;padding:0" class="notice"><%= notice %></p>
<p style="margin:0;padding:0"class="alert"><%= alert %></p>

<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: {class:"form-input form-control"} %>
    <%= link_to_remove_association "Remove", f, class: "form-buttom btn btn-default" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe do |f| %>
  <%= f.input :name, label: 'Name', input_html:{class: 'form-contorl'} %>
  <%= f.input :description, label: 'Description', input_html:{class: 'form-contorl'} %>
  <% if @recipe.image.exists? %>
    <%= image_tag @recipe.image.url(:medium) %>
  <% end %>
  <%= f.input :image, input_html:{class: 'form-contorl'} %>


  <div class="row">
    <div class="col-md-6">
      <h3>Ingredients</h3>
      <div id="ingredients">
        <%= f.simple_fields_for :ingredients do |ingredient| %>
          <%= render 'ingredient_fields', f: ingredient %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Add Ingredients', f, :ingredients, class:"btn btn-default add-button" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h3>Directions</h3>
      <div id="directions">
        <%= f.simple_fields_for :directions do |direction| %>
          <%= render 'direction_fields', f: direction %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Add Directions', f, :directions, class:"btn btn-default add-button" %>
        </div>
      </div>
    </div>
  </div>
  <div class="butt">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: {class:"form-input form-control"} %>
    <%= link_to_remove_association "Remove", f, class: "form-buttom btn btn-default" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to recipe do %>
              <%= image_tag recipe.image.url(:medium) %>
            <% end %>
          </div>
          <h3><%= link_to recipe.name, recipe %></h3>
          <p><%= recipe.description %></p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="main-content">
  <div id="recipe_top" class="row">
    <div class="col-md-4">
      <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
    </div>
    <div class="col-md-8">
      <div id="recipe_info">
        <h1><%= @recipe.name %></h1>
        <p>
          <%= @recipe.description %>
        </p>
        <p>
          Submitted by <%= @recipe.user.email %>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li><%= ingredient.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div id="directions">
        <h2>Direction</h2>
        <ol>
          <% @recipe.directions.each do |direction| %>
            <li><%= direction.step %></li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? && @recipe.user.id == current_user.id %>
  <h5 class="butt">
    <%= link_to 'Confirm', root_path, class:'btn btn-default'%>
    <%= link_to 'Edit', edit_recipe_path, class:'btn btn-default'%>
    <%= link_to 'Delete', recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure?"},class:'btn btn-default' %>
  </h5>
  <% else %>
    <h5 class="butt">
      <%= link_to 'Back', root_path, class:'btn btn-default'%>
    </h5>
<% end %>